- name: Istall Tomcat
  hosts: tomcat_servers      
  become: yes               
  become_method: sudo       
  remote_user: root     
    
  roles:
    - tomcat  

- name: Deploy GitBucket
  hosts: tomcat_servers      
  become: yes               
  become_method: sudo       
  remote_user: root     
    
  roles:
    - gitbucker-deploy