FROM tomcat:9.0.52-jdk8-openjdk

EXPOSE 9191
EXPOSE 45564/tcp
EXPOSE 45564/udp
EXPOSE 4000

RUN mkdir /usr/local/gitbucket

WORKDIR /usr/local/tomcat/conf
COPY server.xml ./

WORKDIR /usr/local/tomcat/webapps
COPY gitbucket.war ./

WORKDIR /usr/local/gitbucket
ADD database.conf ./

WORKDIR /usr/local/gitbucket/plugins
ADD gitbucket-pages-plugin-1.10.0.jar ./gitbucket-pages-plugin-1.9.0.jar