---
    - name: Config Firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
      when: ansible_service_mgr == "systemd"

    - name: Config SELinux
      selinux: state=disabled

    - name: Allow traffic to the necessary NFS services [nfs]
      firewalld:
        service: nfs
        permanent: yes
        state: enabled

    - name: Allow traffic to the necessary NFS services [rpc-bind]
      firewalld:
        service: rpc-bind
        permanent: yes
        state: enabled

    - name: Allow traffic to the necessary NFS services [mountd]
      firewalld:
        service: mountd
        permanent: yes
        state: enabled 

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Install nfs-utils
      yum: name=nfs-utils state=latest

    - name: Enable nfs-utils
      service:
        name: "{{ item }}"
        state: started
        enabled: yes 
      with_items:
        - nfs-utils  
      
    - name: Create a mountable directory if it does not exist
      file:
        path: "{{ nfs_home_folder }}"
        state: directory
        owner: root
        group: root
        mode: '0777'

    - name: Mount an NFS volume
      mount:
        src: "{{ nfs_node1_adress }}:{{ nfs_home_folder }}"
        path: "{{ nfs_home_folder }}"
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs